apiVersion: v1
kind: Template
metadata:
  name: alertmanager-deployment-template

parameters:
- name: ALERTMANAGER_IMAGE_VERSION
  value: v0.8.0

objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: alertmanager
    name: alertmanager
  spec:
    ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
    selector:
      app: alertmanager
      deploymentconfig: alertmanager
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: alertmanager
    name: alertmanager
  spec:
    replicas: 1
    selector:
      app: alertmanager
      deploymentconfig: alertmanager
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      type: Rolling
    template:
      metadata:
        labels:
          app: alertmanager
          deploymentconfig: alertmanager
      spec:
        containers:
        - name: alertmanager
          image: quay.io/prometheus/alertmanager:${ALERTMANAGER_IMAGE_VERSION}
          args:
            - -config.file=/etc/prometheus/alertmanager.yml
            - -storage.path=/data
          imagePullPolicy: IfNotPresent
          name: prometheus
          ports:
          - containerPort: 9093
            protocol: TCP
          resources:
            limits:
              cpu: "100m"
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 256Mi
          volumeMounts:
          - mountPath: /data
            name: alertmanager-data
          - mountPath: /etc/prometheus
            name: prom-alertmanager
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: prom-alertmanager
          name: prom-alertmanager
        - name: alertmanager-data
          persistentVolumeClaim:
            claimName: alertmanager-data
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      app: alertmanager
    name: alertmanager-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 200Gi
    storageClassName: gp2
