apiVersion: v1
kind: Template
metadata:
  name: node-exporter-deployment-template

parameters:
- name: NODE_EXPORTER_IMAGE_VERSION
  value: v0.14.0

objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: prometheus-node-exporter

- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      component: node-exporter
    name: node-exporter
  spec:
    selector:
      matchLabels:
        component: node-exporter
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: node-exporter
        name: node-exporter
      spec:
        containers:
        - image: quay.io/prometheus/node-exporter:${NODE_EXPORTER_IMAGE_VERSION}
          imagePullPolicy: IfNotPresent
          name: node-exporter
          args:
            - --collector.procfs
            - /host/proc
            - --collector.sysfs
            - /host/sys
            - --collector.filesystem.ignored-mount-points
            - "^/(sys|proc|dev|host|etc)($|/)"
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 256Mi
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /host/proc
            name: proc
            readOnly: true
          - mountPath: /host/sys
            name: sys
            readOnly: true
        volumes:
        - hostPath:
            path: /proc
          name: proc
        - hostPath:
            path: /sys
          name: sys
        dnsPolicy: ClusterFirst
        hostNetwork: true
        restartPolicy: Always
        serviceAccount: prometheus-node-exporter
        serviceAccountName: prometheus-node-exporter
        terminationGracePeriodSeconds: 30
    templateGeneration: 1
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
