apiVersion: v1
kind: Template
metadata:
  name: proxy-deployment-template

parameters:
- name: APPS_DOMAIN
  required: true
- name: PROXY_DEFAULT_ADMIN_PASSWORD
  required: true

objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: proxy
    name: proxy
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: proxy
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: proxy
    name: prometheus
  spec:
    host: prometheus.${APPS_DOMAIN}
    port:
      targetPort: http
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: proxy
      weight: 100
    wildcardPolicy: None

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: proxy
    name: grafana
  spec:
    host: grafana.${APPS_DOMAIN}
    port:
      targetPort: http
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: proxy
      weight: 100
    wildcardPolicy: None


- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: proxy
    name: alertmanager
  spec:
    host: alertmanager.${APPS_DOMAIN}
    port:
      targetPort: http
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: proxy
      weight: 100
    wildcardPolicy: None

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: proxy
    name: proxy
  spec:
    replicas: 1
    selector:
      app: proxy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 100%
        maxUnavailable: 50%
        timeoutSeconds: 60
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: proxy
      spec:
        containers:
        - env:
          - name: PROXY_ROUTE_TO_SERVICE
            # Space separated list of "<fqdn>,<service-name:service-port>" mapping
            value: |-
              prometheus.${APPS_DOMAIN},prometheus:9090
              grafana.${APPS_DOMAIN},grafana:3000
              alertmanager.${APPS_DOMAIN},alertmanager:909
              pushgateway.${APPS_DOMAIN},pushgateway:9091
          - name: PROXY_DEFAULT_ADMIN_PASSWORD
            value: ${PROXY_DEFAULT_ADMIN_PASSWORD}
          image: getupcloud/nginx-proxy:latest
          imagePullPolicy: IfNotPresent
          name: proxy
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
          - mountPath: /opt/app-root/proxy
            name: proxyconf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: proxyconf
          name: proxyconf
    triggers:
    - type: ConfigChange
