apiVersion: v1
kind: Template
metadata:
  name: proxy-config-template

parameters:
- name: PROXY_ADMIN_HTPASSWD_HASH
  required: true

objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: proxy-htpasswd
  data:
    .htpasswd: |
      ${PROXY_ADMIN_HTPASSWD_HASH}
