apiVersion: v1
kind: List

items:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: eventrouter-exporter
  rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - events
    verbs:
    - get
    - list
    - watch

